/*
 * Flat config, using `eslint-config-next`'s own flat exports.
 *
 * This used to go through `FlatCompat` from `@eslint/eslintrc`, translating the old
 * `extends: ['next/core-web-vitals', 'next/typescript']` shorthand. That stopped working:
 * `@eslint/eslintrc` is not a declared dependency of this package (so `bun run lint` failed to
 * resolve it at all), and once resolved it threw `Converting circular structure to JSON` —
 * eslintrc's validator tries to serialise the config for its error message, and
 * eslint-plugin-react's flat config is self-referential.
 *
 * None of that translation is needed any more: since v15 `eslint-config-next` publishes flat
 * config arrays under its own subpath exports, so they are spread in directly and the
 * compatibility layer is gone.
 */
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypeScript from 'eslint-config-next/typescript'

const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    rules: {
      '@typescript-eslint/ban-ts-comment': 'warn',
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          vars: 'all',
          args: 'after-used',
          ignoreRestSiblings: false,
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^(_|ignore)',
        },
      ],
    },
  },
  {
    // Generated by `payload generate:types` / the db adapter; not ours to lint.
    ignores: ['.next/', 'src/payload-types.ts', 'src/payload-generated-schema.ts'],
  },
]

export default eslintConfig
