/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SanPhamCuaEmRouteImport } from './routes/san-pham-cua-em'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as HocTapRouteImport } from './routes/hoc-tap'
import { Route as DieuKhoanSuDungRouteImport } from './routes/dieu-khoan-su-dung'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChinhSachBaoMatRouteImport } from './routes/chinh-sach-bao-mat'
import { Route as BangXepHangRouteImport } from './routes/bang-xep-hang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HocTapIndexRouteImport } from './routes/hoc-tap.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as HocTapQuyen2RouteImport } from './routes/hoc-tap.quyen-2'
import { Route as HocTapQuyen1RouteImport } from './routes/hoc-tap.quyen-1'
import { Route as HocTapLuyenNoiRouteImport } from './routes/hoc-tap.luyen-noi'
import { Route as HocTapBangChuCaiRouteImport } from './routes/hoc-tap.bang-chu-cai'
import { Route as ApiTtsRouteImport } from './routes/api.tts'
import { Route as ApiAvatarRouteImport } from './routes/api.avatar'
import { Route as HocTapQuyen1IndexRouteImport } from './routes/hoc-tap.quyen-1.index'
import { Route as HocTapQuyen1ChangIdRouteImport } from './routes/hoc-tap_.quyen-1_.$changId'
import { Route as HocTapQuyen1ChuDeChar123chuDeIndexChar125RouteImport } from './routes/hoc-tap.quyen-1.chu-de-{$chuDeIndex}'
import { Route as HocTapLuyenNoiChuDeIdRouteImport } from './routes/hoc-tap.luyen-noi.$chuDeId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamCuaEmRoute = SanPhamCuaEmRouteImport.update({
  id: '/san-pham-cua-em',
  path: '/san-pham-cua-em',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HocTapRoute = HocTapRouteImport.update({
  id: '/hoc-tap',
  path: '/hoc-tap',
  getParentRoute: () => rootRouteImport,
} as any)
const DieuKhoanSuDungRoute = DieuKhoanSuDungRouteImport.update({
  id: '/dieu-khoan-su-dung',
  path: '/dieu-khoan-su-dung',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachBaoMatRoute = ChinhSachBaoMatRouteImport.update({
  id: '/chinh-sach-bao-mat',
  path: '/chinh-sach-bao-mat',
  getParentRoute: () => rootRouteImport,
} as any)
const BangXepHangRoute = BangXepHangRouteImport.update({
  id: '/bang-xep-hang',
  path: '/bang-xep-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HocTapIndexRoute = HocTapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HocTapRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const HocTapQuyen2Route = HocTapQuyen2RouteImport.update({
  id: '/quyen-2',
  path: '/quyen-2',
  getParentRoute: () => HocTapRoute,
} as any)
const HocTapQuyen1Route = HocTapQuyen1RouteImport.update({
  id: '/quyen-1',
  path: '/quyen-1',
  getParentRoute: () => HocTapRoute,
} as any)
const HocTapLuyenNoiRoute = HocTapLuyenNoiRouteImport.update({
  id: '/luyen-noi',
  path: '/luyen-noi',
  getParentRoute: () => HocTapRoute,
} as any)
const HocTapBangChuCaiRoute = HocTapBangChuCaiRouteImport.update({
  id: '/bang-chu-cai',
  path: '/bang-chu-cai',
  getParentRoute: () => HocTapRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const HocTapQuyen1IndexRoute = HocTapQuyen1IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HocTapQuyen1Route,
} as any)
const HocTapQuyen1ChangIdRoute = HocTapQuyen1ChangIdRouteImport.update({
  id: '/hoc-tap_/quyen-1_/$changId',
  path: '/hoc-tap/quyen-1/$changId',
  getParentRoute: () => rootRouteImport,
} as any)
const HocTapQuyen1ChuDeChar123chuDeIndexChar125Route =
  HocTapQuyen1ChuDeChar123chuDeIndexChar125RouteImport.update({
    id: '/chu-de-{$chuDeIndex}',
    path: '/chu-de-{$chuDeIndex}',
    getParentRoute: () => HocTapQuyen1Route,
  } as any)
const HocTapLuyenNoiChuDeIdRoute = HocTapLuyenNoiChuDeIdRouteImport.update({
  id: '/$chuDeId',
  path: '/$chuDeId',
  getParentRoute: () => HocTapLuyenNoiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bang-xep-hang': typeof BangXepHangRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/dashboard': typeof DashboardRoute
  '/dieu-khoan-su-dung': typeof DieuKhoanSuDungRoute
  '/hoc-tap': typeof HocTapRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/san-pham-cua-em': typeof SanPhamCuaEmRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/tts': typeof ApiTtsRoute
  '/hoc-tap/bang-chu-cai': typeof HocTapBangChuCaiRoute
  '/hoc-tap/luyen-noi': typeof HocTapLuyenNoiRouteWithChildren
  '/hoc-tap/quyen-1': typeof HocTapQuyen1RouteWithChildren
  '/hoc-tap/quyen-2': typeof HocTapQuyen2Route
  '/u/$username': typeof UUsernameRoute
  '/hoc-tap/': typeof HocTapIndexRoute
  '/hoc-tap/luyen-noi/$chuDeId': typeof HocTapLuyenNoiChuDeIdRoute
  '/hoc-tap/quyen-1/chu-de-{$chuDeIndex}': typeof HocTapQuyen1ChuDeChar123chuDeIndexChar125Route
  '/hoc-tap/quyen-1/$changId': typeof HocTapQuyen1ChangIdRoute
  '/hoc-tap/quyen-1/': typeof HocTapQuyen1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bang-xep-hang': typeof BangXepHangRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/dashboard': typeof DashboardRoute
  '/dieu-khoan-su-dung': typeof DieuKhoanSuDungRoute
  '/reset-password': typeof ResetPasswordRoute
  '/san-pham-cua-em': typeof SanPhamCuaEmRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/tts': typeof ApiTtsRoute
  '/hoc-tap/bang-chu-cai': typeof HocTapBangChuCaiRoute
  '/hoc-tap/luyen-noi': typeof HocTapLuyenNoiRouteWithChildren
  '/hoc-tap/quyen-2': typeof HocTapQuyen2Route
  '/u/$username': typeof UUsernameRoute
  '/hoc-tap': typeof HocTapIndexRoute
  '/hoc-tap/luyen-noi/$chuDeId': typeof HocTapLuyenNoiChuDeIdRoute
  '/hoc-tap/quyen-1/chu-de-{$chuDeIndex}': typeof HocTapQuyen1ChuDeChar123chuDeIndexChar125Route
  '/hoc-tap/quyen-1/$changId': typeof HocTapQuyen1ChangIdRoute
  '/hoc-tap/quyen-1': typeof HocTapQuyen1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bang-xep-hang': typeof BangXepHangRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/dashboard': typeof DashboardRoute
  '/dieu-khoan-su-dung': typeof DieuKhoanSuDungRoute
  '/hoc-tap': typeof HocTapRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/san-pham-cua-em': typeof SanPhamCuaEmRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/tts': typeof ApiTtsRoute
  '/hoc-tap/bang-chu-cai': typeof HocTapBangChuCaiRoute
  '/hoc-tap/luyen-noi': typeof HocTapLuyenNoiRouteWithChildren
  '/hoc-tap/quyen-1': typeof HocTapQuyen1RouteWithChildren
  '/hoc-tap/quyen-2': typeof HocTapQuyen2Route
  '/u/$username': typeof UUsernameRoute
  '/hoc-tap/': typeof HocTapIndexRoute
  '/hoc-tap/luyen-noi/$chuDeId': typeof HocTapLuyenNoiChuDeIdRoute
  '/hoc-tap/quyen-1/chu-de-{$chuDeIndex}': typeof HocTapQuyen1ChuDeChar123chuDeIndexChar125Route
  '/hoc-tap_/quyen-1_/$changId': typeof HocTapQuyen1ChangIdRoute
  '/hoc-tap/quyen-1/': typeof HocTapQuyen1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bang-xep-hang'
    | '/chinh-sach-bao-mat'
    | '/dashboard'
    | '/dieu-khoan-su-dung'
    | '/hoc-tap'
    | '/reset-password'
    | '/san-pham-cua-em'
    | '/sitemap.xml'
    | '/api/avatar'
    | '/api/tts'
    | '/hoc-tap/bang-chu-cai'
    | '/hoc-tap/luyen-noi'
    | '/hoc-tap/quyen-1'
    | '/hoc-tap/quyen-2'
    | '/u/$username'
    | '/hoc-tap/'
    | '/hoc-tap/luyen-noi/$chuDeId'
    | '/hoc-tap/quyen-1/chu-de-{$chuDeIndex}'
    | '/hoc-tap/quyen-1/$changId'
    | '/hoc-tap/quyen-1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bang-xep-hang'
    | '/chinh-sach-bao-mat'
    | '/dashboard'
    | '/dieu-khoan-su-dung'
    | '/reset-password'
    | '/san-pham-cua-em'
    | '/sitemap.xml'
    | '/api/avatar'
    | '/api/tts'
    | '/hoc-tap/bang-chu-cai'
    | '/hoc-tap/luyen-noi'
    | '/hoc-tap/quyen-2'
    | '/u/$username'
    | '/hoc-tap'
    | '/hoc-tap/luyen-noi/$chuDeId'
    | '/hoc-tap/quyen-1/chu-de-{$chuDeIndex}'
    | '/hoc-tap/quyen-1/$changId'
    | '/hoc-tap/quyen-1'
  id:
    | '__root__'
    | '/'
    | '/bang-xep-hang'
    | '/chinh-sach-bao-mat'
    | '/dashboard'
    | '/dieu-khoan-su-dung'
    | '/hoc-tap'
    | '/reset-password'
    | '/san-pham-cua-em'
    | '/sitemap.xml'
    | '/api/avatar'
    | '/api/tts'
    | '/hoc-tap/bang-chu-cai'
    | '/hoc-tap/luyen-noi'
    | '/hoc-tap/quyen-1'
    | '/hoc-tap/quyen-2'
    | '/u/$username'
    | '/hoc-tap/'
    | '/hoc-tap/luyen-noi/$chuDeId'
    | '/hoc-tap/quyen-1/chu-de-{$chuDeIndex}'
    | '/hoc-tap_/quyen-1_/$changId'
    | '/hoc-tap/quyen-1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BangXepHangRoute: typeof BangXepHangRoute
  ChinhSachBaoMatRoute: typeof ChinhSachBaoMatRoute
  DashboardRoute: typeof DashboardRoute
  DieuKhoanSuDungRoute: typeof DieuKhoanSuDungRoute
  HocTapRoute: typeof HocTapRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SanPhamCuaEmRoute: typeof SanPhamCuaEmRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAvatarRoute: typeof ApiAvatarRoute
  ApiTtsRoute: typeof ApiTtsRoute
  UUsernameRoute: typeof UUsernameRoute
  HocTapQuyen1ChangIdRoute: typeof HocTapQuyen1ChangIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham-cua-em': {
      id: '/san-pham-cua-em'
      path: '/san-pham-cua-em'
      fullPath: '/san-pham-cua-em'
      preLoaderRoute: typeof SanPhamCuaEmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-tap': {
      id: '/hoc-tap'
      path: '/hoc-tap'
      fullPath: '/hoc-tap'
      preLoaderRoute: typeof HocTapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieu-khoan-su-dung': {
      id: '/dieu-khoan-su-dung'
      path: '/dieu-khoan-su-dung'
      fullPath: '/dieu-khoan-su-dung'
      preLoaderRoute: typeof DieuKhoanSuDungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-bao-mat': {
      id: '/chinh-sach-bao-mat'
      path: '/chinh-sach-bao-mat'
      fullPath: '/chinh-sach-bao-mat'
      preLoaderRoute: typeof ChinhSachBaoMatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bang-xep-hang': {
      id: '/bang-xep-hang'
      path: '/bang-xep-hang'
      fullPath: '/bang-xep-hang'
      preLoaderRoute: typeof BangXepHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-tap/': {
      id: '/hoc-tap/'
      path: '/'
      fullPath: '/hoc-tap/'
      preLoaderRoute: typeof HocTapIndexRouteImport
      parentRoute: typeof HocTapRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-tap/quyen-2': {
      id: '/hoc-tap/quyen-2'
      path: '/quyen-2'
      fullPath: '/hoc-tap/quyen-2'
      preLoaderRoute: typeof HocTapQuyen2RouteImport
      parentRoute: typeof HocTapRoute
    }
    '/hoc-tap/quyen-1': {
      id: '/hoc-tap/quyen-1'
      path: '/quyen-1'
      fullPath: '/hoc-tap/quyen-1'
      preLoaderRoute: typeof HocTapQuyen1RouteImport
      parentRoute: typeof HocTapRoute
    }
    '/hoc-tap/luyen-noi': {
      id: '/hoc-tap/luyen-noi'
      path: '/luyen-noi'
      fullPath: '/hoc-tap/luyen-noi'
      preLoaderRoute: typeof HocTapLuyenNoiRouteImport
      parentRoute: typeof HocTapRoute
    }
    '/hoc-tap/bang-chu-cai': {
      id: '/hoc-tap/bang-chu-cai'
      path: '/bang-chu-cai'
      fullPath: '/hoc-tap/bang-chu-cai'
      preLoaderRoute: typeof HocTapBangChuCaiRouteImport
      parentRoute: typeof HocTapRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-tap/quyen-1/': {
      id: '/hoc-tap/quyen-1/'
      path: '/'
      fullPath: '/hoc-tap/quyen-1/'
      preLoaderRoute: typeof HocTapQuyen1IndexRouteImport
      parentRoute: typeof HocTapQuyen1Route
    }
    '/hoc-tap_/quyen-1_/$changId': {
      id: '/hoc-tap_/quyen-1_/$changId'
      path: '/hoc-tap/quyen-1/$changId'
      fullPath: '/hoc-tap/quyen-1/$changId'
      preLoaderRoute: typeof HocTapQuyen1ChangIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-tap/quyen-1/chu-de-{$chuDeIndex}': {
      id: '/hoc-tap/quyen-1/chu-de-{$chuDeIndex}'
      path: '/chu-de-{$chuDeIndex}'
      fullPath: '/hoc-tap/quyen-1/chu-de-{$chuDeIndex}'
      preLoaderRoute: typeof HocTapQuyen1ChuDeChar123chuDeIndexChar125RouteImport
      parentRoute: typeof HocTapQuyen1Route
    }
    '/hoc-tap/luyen-noi/$chuDeId': {
      id: '/hoc-tap/luyen-noi/$chuDeId'
      path: '/$chuDeId'
      fullPath: '/hoc-tap/luyen-noi/$chuDeId'
      preLoaderRoute: typeof HocTapLuyenNoiChuDeIdRouteImport
      parentRoute: typeof HocTapLuyenNoiRoute
    }
  }
}

interface HocTapLuyenNoiRouteChildren {
  HocTapLuyenNoiChuDeIdRoute: typeof HocTapLuyenNoiChuDeIdRoute
}

const HocTapLuyenNoiRouteChildren: HocTapLuyenNoiRouteChildren = {
  HocTapLuyenNoiChuDeIdRoute: HocTapLuyenNoiChuDeIdRoute,
}

const HocTapLuyenNoiRouteWithChildren = HocTapLuyenNoiRoute._addFileChildren(
  HocTapLuyenNoiRouteChildren,
)

interface HocTapQuyen1RouteChildren {
  HocTapQuyen1ChuDeChar123chuDeIndexChar125Route: typeof HocTapQuyen1ChuDeChar123chuDeIndexChar125Route
  HocTapQuyen1IndexRoute: typeof HocTapQuyen1IndexRoute
}

const HocTapQuyen1RouteChildren: HocTapQuyen1RouteChildren = {
  HocTapQuyen1ChuDeChar123chuDeIndexChar125Route:
    HocTapQuyen1ChuDeChar123chuDeIndexChar125Route,
  HocTapQuyen1IndexRoute: HocTapQuyen1IndexRoute,
}

const HocTapQuyen1RouteWithChildren = HocTapQuyen1Route._addFileChildren(
  HocTapQuyen1RouteChildren,
)

interface HocTapRouteChildren {
  HocTapBangChuCaiRoute: typeof HocTapBangChuCaiRoute
  HocTapLuyenNoiRoute: typeof HocTapLuyenNoiRouteWithChildren
  HocTapQuyen1Route: typeof HocTapQuyen1RouteWithChildren
  HocTapQuyen2Route: typeof HocTapQuyen2Route
  HocTapIndexRoute: typeof HocTapIndexRoute
}

const HocTapRouteChildren: HocTapRouteChildren = {
  HocTapBangChuCaiRoute: HocTapBangChuCaiRoute,
  HocTapLuyenNoiRoute: HocTapLuyenNoiRouteWithChildren,
  HocTapQuyen1Route: HocTapQuyen1RouteWithChildren,
  HocTapQuyen2Route: HocTapQuyen2Route,
  HocTapIndexRoute: HocTapIndexRoute,
}

const HocTapRouteWithChildren =
  HocTapRoute._addFileChildren(HocTapRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BangXepHangRoute: BangXepHangRoute,
  ChinhSachBaoMatRoute: ChinhSachBaoMatRoute,
  DashboardRoute: DashboardRoute,
  DieuKhoanSuDungRoute: DieuKhoanSuDungRoute,
  HocTapRoute: HocTapRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SanPhamCuaEmRoute: SanPhamCuaEmRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAvatarRoute: ApiAvatarRoute,
  ApiTtsRoute: ApiTtsRoute,
  UUsernameRoute: UUsernameRoute,
  HocTapQuyen1ChangIdRoute: HocTapQuyen1ChangIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
