/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SanPhamCuaEmRouteImport } from './routes/san-pham-cua-em'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as HocTiengVietRouteImport } from './routes/hoc-tieng-viet'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BangXepHangRouteImport } from './routes/bang-xep-hang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HocTiengVietIndexRouteImport } from './routes/hoc-tieng-viet.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as HocTiengVietChangIdRouteImport } from './routes/hoc-tieng-viet.$changId'

const SanPhamCuaEmRoute = SanPhamCuaEmRouteImport.update({
  id: '/san-pham-cua-em',
  path: '/san-pham-cua-em',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HocTiengVietRoute = HocTiengVietRouteImport.update({
  id: '/hoc-tieng-viet',
  path: '/hoc-tieng-viet',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BangXepHangRoute = BangXepHangRouteImport.update({
  id: '/bang-xep-hang',
  path: '/bang-xep-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HocTiengVietIndexRoute = HocTiengVietIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HocTiengVietRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const HocTiengVietChangIdRoute = HocTiengVietChangIdRouteImport.update({
  id: '/$changId',
  path: '/$changId',
  getParentRoute: () => HocTiengVietRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bang-xep-hang': typeof BangXepHangRoute
  '/dashboard': typeof DashboardRoute
  '/hoc-tieng-viet': typeof HocTiengVietRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/san-pham-cua-em': typeof SanPhamCuaEmRoute
  '/hoc-tieng-viet/$changId': typeof HocTiengVietChangIdRoute
  '/u/$username': typeof UUsernameRoute
  '/hoc-tieng-viet/': typeof HocTiengVietIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bang-xep-hang': typeof BangXepHangRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/san-pham-cua-em': typeof SanPhamCuaEmRoute
  '/hoc-tieng-viet/$changId': typeof HocTiengVietChangIdRoute
  '/u/$username': typeof UUsernameRoute
  '/hoc-tieng-viet': typeof HocTiengVietIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bang-xep-hang': typeof BangXepHangRoute
  '/dashboard': typeof DashboardRoute
  '/hoc-tieng-viet': typeof HocTiengVietRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/san-pham-cua-em': typeof SanPhamCuaEmRoute
  '/hoc-tieng-viet/$changId': typeof HocTiengVietChangIdRoute
  '/u/$username': typeof UUsernameRoute
  '/hoc-tieng-viet/': typeof HocTiengVietIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bang-xep-hang'
    | '/dashboard'
    | '/hoc-tieng-viet'
    | '/reset-password'
    | '/san-pham-cua-em'
    | '/hoc-tieng-viet/$changId'
    | '/u/$username'
    | '/hoc-tieng-viet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bang-xep-hang'
    | '/dashboard'
    | '/reset-password'
    | '/san-pham-cua-em'
    | '/hoc-tieng-viet/$changId'
    | '/u/$username'
    | '/hoc-tieng-viet'
  id:
    | '__root__'
    | '/'
    | '/bang-xep-hang'
    | '/dashboard'
    | '/hoc-tieng-viet'
    | '/reset-password'
    | '/san-pham-cua-em'
    | '/hoc-tieng-viet/$changId'
    | '/u/$username'
    | '/hoc-tieng-viet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BangXepHangRoute: typeof BangXepHangRoute
  DashboardRoute: typeof DashboardRoute
  HocTiengVietRoute: typeof HocTiengVietRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SanPhamCuaEmRoute: typeof SanPhamCuaEmRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/san-pham-cua-em': {
      id: '/san-pham-cua-em'
      path: '/san-pham-cua-em'
      fullPath: '/san-pham-cua-em'
      preLoaderRoute: typeof SanPhamCuaEmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-tieng-viet': {
      id: '/hoc-tieng-viet'
      path: '/hoc-tieng-viet'
      fullPath: '/hoc-tieng-viet'
      preLoaderRoute: typeof HocTiengVietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bang-xep-hang': {
      id: '/bang-xep-hang'
      path: '/bang-xep-hang'
      fullPath: '/bang-xep-hang'
      preLoaderRoute: typeof BangXepHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-tieng-viet/': {
      id: '/hoc-tieng-viet/'
      path: '/'
      fullPath: '/hoc-tieng-viet/'
      preLoaderRoute: typeof HocTiengVietIndexRouteImport
      parentRoute: typeof HocTiengVietRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-tieng-viet/$changId': {
      id: '/hoc-tieng-viet/$changId'
      path: '/$changId'
      fullPath: '/hoc-tieng-viet/$changId'
      preLoaderRoute: typeof HocTiengVietChangIdRouteImport
      parentRoute: typeof HocTiengVietRoute
    }
  }
}

interface HocTiengVietRouteChildren {
  HocTiengVietChangIdRoute: typeof HocTiengVietChangIdRoute
  HocTiengVietIndexRoute: typeof HocTiengVietIndexRoute
}

const HocTiengVietRouteChildren: HocTiengVietRouteChildren = {
  HocTiengVietChangIdRoute: HocTiengVietChangIdRoute,
  HocTiengVietIndexRoute: HocTiengVietIndexRoute,
}

const HocTiengVietRouteWithChildren = HocTiengVietRoute._addFileChildren(
  HocTiengVietRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BangXepHangRoute: BangXepHangRoute,
  DashboardRoute: DashboardRoute,
  HocTiengVietRoute: HocTiengVietRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SanPhamCuaEmRoute: SanPhamCuaEmRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
