// 5-accent stage palette — green / sky / violet / amber / rose — driven by the
// --stage-N / --stage-N-deep / --stage-N-soft CSS tokens defined in src/styles.css.
// Indexed by chặng position and reused wherever a stage needs its own colour (lesson pages,
// speaking practice, the alphabet grid).
export const STAGE_COLORS = [
  {
    ring: "ring-stage-1",
    bg: "bg-stage-1",
    bgSoft: "bg-stage-1-soft",
    gradient: "bg-gradient-to-br from-stage-1 to-stage-1-deep",
    gradientHover: "from-stage-1 to-stage-1",
    border: "border-stage-1",
    text: "text-stage-1-deep",
    stripe: "from-stage-1 to-stage-1-deep",
    glow: "shadow-[0_8px_24px_-4px_var(--stage-1)]",
    bevel: "shadow-bevel-stage-1",
    hex: "var(--stage-1)",
    bevelActive: "active:shadow-bevel-stage-1-active",
    scrollThumb: "var(--stage-1)",
    scrollTrack: "var(--stage-1-soft)",
  },
  {
    ring: "ring-stage-2",
    bg: "bg-stage-2",
    bgSoft: "bg-stage-2-soft",
    gradient: "bg-gradient-to-br from-stage-2 to-stage-2-deep",
    gradientHover: "from-stage-2 to-stage-2",
    border: "border-stage-2",
    text: "text-stage-2-deep",
    stripe: "from-stage-2 to-stage-2-deep",
    glow: "shadow-[0_8px_24px_-4px_var(--stage-2)]",
    bevel: "shadow-bevel-stage-2",
    hex: "var(--stage-2)",
    bevelActive: "active:shadow-bevel-stage-2-active",
    scrollThumb: "var(--stage-2)",
    scrollTrack: "var(--stage-2-soft)",
  },
  {
    ring: "ring-stage-3",
    bg: "bg-stage-3",
    bgSoft: "bg-stage-3-soft",
    gradient: "bg-gradient-to-br from-stage-3 to-stage-3-deep",
    gradientHover: "from-stage-3 to-stage-3",
    border: "border-stage-3",
    text: "text-stage-3-deep",
    stripe: "from-stage-3 to-stage-3-deep",
    glow: "shadow-[0_8px_24px_-4px_var(--stage-3)]",
    bevel: "shadow-bevel-stage-3",
    hex: "var(--stage-3)",
    bevelActive: "active:shadow-bevel-stage-3-active",
    scrollThumb: "var(--stage-3)",
    scrollTrack: "var(--stage-3-soft)",
  },
  {
    ring: "ring-stage-4",
    bg: "bg-stage-4",
    bgSoft: "bg-stage-4-soft",
    gradient: "bg-gradient-to-br from-stage-4 to-stage-4-deep",
    gradientHover: "from-stage-4 to-stage-4",
    border: "border-stage-4",
    text: "text-stage-4-deep",
    stripe: "from-stage-4 to-stage-4-deep",
    glow: "shadow-[0_8px_24px_-4px_var(--stage-4)]",
    bevel: "shadow-bevel-stage-4",
    hex: "var(--stage-4)",
    bevelActive: "active:shadow-bevel-stage-4-active",
    scrollThumb: "var(--stage-4)",
    scrollTrack: "var(--stage-4-soft)",
  },
  {
    ring: "ring-stage-5",
    bg: "bg-stage-5",
    bgSoft: "bg-stage-5-soft",
    gradient: "bg-gradient-to-br from-stage-5 to-stage-5-deep",
    gradientHover: "from-stage-5 to-stage-5",
    border: "border-stage-5",
    text: "text-stage-5-deep",
    stripe: "from-stage-5 to-stage-5-deep",
    glow: "shadow-[0_8px_24px_-4px_var(--stage-5)]",
    bevel: "shadow-bevel-stage-5",
    hex: "var(--stage-5)",
    bevelActive: "active:shadow-bevel-stage-5-active",
    scrollThumb: "var(--stage-5)",
    scrollTrack: "var(--stage-5-soft)",
  },
];
